### PR TITLE
Update To .net5

### PR DESCRIPTION
**Pull request by rootflood**
Update To .net5 to make sure benches are same in .net5

### CODE REVIEW

**Comment by rootflood** [comment]
also about :
```C#
    [MemoryDiagnoser]
    public class DynamicBenchmark
    {

        [Params(100)]
        public int N;

        [GlobalSetup]
        public void GlobalS()
        {
            StringConcat_V = "";
            DynamicStringConcat_V = "";
            FormatUser_V = new DynamicUser("John Billon", "Arlington", 23);
            DynamicallyFormatUser_V = FormatUser_V;
            StructFormatUser_V = new DynamicStruct();
            StructDynamicallyFormatUser_V = StructFormatUser_V;
        }

        private string StringConcat_V;
        [Benchmark]
        public object StringConcat()
        {
            var StringConcat_V = this.StringConcat_V;
            string message = "Message";
            for (int i = 0; i < N; i++)
                StringConcat_V = this.StringConcat_V + StringConcat_V;
            return StringConcat_V;
        }

        private dynamic DynamicStringConcat_V;
        [Benchmark]
        public object DynamicStringConcat()
        {
            var DynamicStringConcat_V = this.DynamicStringConcat_V;
            string message = "Message";
            for (int i = 0; i < N; i++)
                DynamicStringConcat_V = this.DynamicStringConcat_V + DynamicStringConcat_V;
            return DynamicStringConcat_V;
        }


        public DynamicUser FormatUser_V;
        [Benchmark]
        public object FormatUser()
        {
            var FormatUser_V = this.FormatUser_V;
            for (int i = 0; i < N; i++)
            {
                FormatUser_V.UpdateName("Crazy");
            }
            return FormatUser_V;
        }

        private dynamic DynamicallyFormatUser_V;
        [Benchmark]
        public object DynamicallyFormatUser()
        {
            var DynamicallyFormatUser_V = this.DynamicallyFormatUser_V;
            for (int i = 0; i < N; i++)
            {
                DynamicallyFormatUser_V.UpdateName("Crazy");
            }
            return DynamicallyFormatUser_V;
        }

        private DynamicStruct StructFormatUser_V;
        [Benchmark]
        public object StructFormatUser()
        {
            var StructFormatUser_V = this.StructFormatUser_V;
            for (int i = 0; i < N; i++)
            {
                StructFormatUser_V.UpdateName("Crazy");
            }
            return StructFormatUser_V;
        }

        public dynamic StructDynamicallyFormatUser_V;
        [Benchmark]
        public object StructDynamicallyFormatUser()
        {
            var StructDynamicallyFormatUser_V = this.StructDynamicallyFormatUser_V;
            for (int i = 0; i < N; i++)
            {
                StructDynamicallyFormatUser_V.UpdateName("Crazy");
            }
            return StructDynamicallyFormatUser_V;
        }
    }
```

reason:
>The string concat was roughly the same performance, which was a little surprising to me.

and result:
|                      Method |   N |        Mean |     Error |    StdDev |      Median |  Gen 0 | Allocated |
|---------------------------- |---- |------------:|----------:|----------:|------------:|-------:|----------:|
|                StringConcat | 100 |   377.02 ns |  4.134 ns |  3.665 ns |   374.69 ns |      - |         - |
|         DynamicStringConcat | 100 | 1,155.33 ns | 25.712 ns | 75.812 ns | 1,132.69 ns |      - |         - |
|                  FormatUser | 100 |   290.56 ns |  5.206 ns |  4.347 ns |   291.93 ns |      - |         - |
|       DynamicallyFormatUser | 100 |   989.07 ns | 16.828 ns | 14.918 ns |   989.65 ns |      - |         - |
|            StructFormatUser | 100 |    94.94 ns |  0.846 ns |  0.750 ns |    94.83 ns | 0.0126 |      40 B |
| StructDynamicallyFormatUser | 100 |   991.92 ns | 14.787 ns | 13.831 ns |   990.57 ns |      - |         - |

**Comment by morgankenyon** [comment]
Hey @rootflood. Sorry for losing track of your initial commit. 

I see your updates tease out some differences in performance in dynamic strings.

Were you just curious about how .net5 performance was compared to .net22?

**Comment by rootflood** [comment]
hi @morgankenyon 
>Were you just curious about how .net5 performance was compared to .net22?

no, i just try to update to .net5 to ensure the valid benchmark results, however its not important part about the commit
important part is about C# auto optimizations which you can see it in [this link in sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGAzAATakAiAngHYCGAtgJZgBCMtYAFo/VAGtCAb0KlxE8SXIoqdJqwDKAFyjNaAcwDCELvWUB9CABsAJgAoAlGMkTRBW49Kn5LMKUh7lMU6QC8pABEgQDcNk4SGDgADKSMMADOCfQaMP5BALKJyamh4REeumD6PunxSSlpANSFXj4AdAAqECpqmlZhDk4Avvn5kgAOagBuJc6urHIMbq3q2kX6BgBqnRHSEMAAVjBgylMKYLOaOl4GtDAA7lb9djeOo1D7M6pzJ8WGS+nK3MwJ9TTTJQvY4LD6rApSGJxbKVdKBLIVXLgiEAg5HeanT4Bb6/f4TQ7AjHvZakGqo55tImLFZ3WwYADsTyBlLe1ORtl6XXEhG6QA=)
the C# will optimize dynamic object if a strong type assigned to it.
also i didn't use the "message" variable because when string length is growing the benchmark will have extra timing for that code.

sorry about closed commit, i was thoutgh this commit isn't important because of not responding and i deleted the folk too so i can't reopen it, but if you think this could help i can create other commit for it.

**Comment by morgankenyon** [comment]
That's right, thank you for pointing that out. I can see you added my comment about being surprised about performance being equivalent. 

Yeah, I think there's value in it. I'd like to keep the original just because that's what the blog post is referencing. But if you wanted to either add what you've done as a second benchmark file, or just extra tests in the same benchmark that would be very handy to compare again.

**Pull request closed without merging**
